version: '3.8'

services:
  ptm-database:
    image: mariadb:latest
    container_name: ptm-mariadb
    env_file: ./.env
    environment:
      TZ: Europe/Lisbon
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASS
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASS
      MYSQL_DATABASE: $DB_DATABASE
    ports:
      - $DB_PORT:$DB_DOCKER_PORT
    volumes:
      - DB:/var/lib/mysql
      # copy the sql script to db init
      - ./api/data/init.sql:/docker-entrypoint-initdb.d/init.sql
      #- /etc/localtime:/etc/localtime:ro
      #- /etc/timezone:/etc/timezone:ro
    networks:
      - ptm-network
    restart: always
    #command: ['mysqld','--default-time-zone=Europe/Lisbon']

  ptm-server:
#    image:  ghcr.io/ptv1p3r/ptm_api:latest
    build: ./
    env_file: ./.env
    ports:
      - $NODE_PORT:$NODE_DOCKER_PORT
    depends_on:
      - ptm-database
    environment:
      - DB_HOST=ptm-database
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_ROOT_PASS
      - DB_NAME=$DB_DATABASE
      - DB_PORT=$DB_DOCKER_PORT
      - TZ=Europe/Lisbon
    networks:
      - ptm-network
    restart: always

volumes:
  DB:
#    driver: local

networks:
  ptm-network:
    driver: bridge
