const SUCCESS_CODE = {
    OK: 200,
    CREATED: 201,
    ACCEPTED: 202,
    NO_CONTENT: 204,
}

const ERROR_CODE = {
    BAD_REQUEST: 404,
    UNAUTHORIZED: 401,
    PAYMENT_REQUIRED: 402,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
}

const SERVER_CODE = {
    INTERNAL_SERVER_ERROR: 501,
    BAD_GATEWAY: 502,
    SERVICE_UNAVAILABLE: 503,
    NETWORK_AUTHENTICATION_REQUIRED: 511
}


module.exports = {
    SUCCESS_CODE,
    ERROR_CODE,
    SERVER_CODE,
};
